student = int(input("รหัสนักเรียน: "))
nickname = input("ชื่อเล่น: ")
age = int(input("อายุ: "))
item = input("ต้องการยืมใช้อะไรดี: ")

print("\n" + "=" * 50 + "\n" + "Welcome to Pre-Engineering & Robotics\n")
print("สวัสดีครับ กรอกข้อมูลตนเองครับผม")
print("ชื่อเล่น:", nickname)
print("รหัสนักเรียน:", student)
print("อายุ:", age, "ปี")
print("ต้องการยืม:", item)